"""Gate round 14 (hw-1qheu): the thirteenth cross-model gate report (4 MAJOR + 1 MINOR)
and the mayor's Fable read of round 13 (1 MINOR), one ruling each.

T1  ../gmail-api.py `thread --json`: the selected body is DEMONSTRABLY present before a
    row is reported complete — a text part with neither data nor an attachment id is
    unavailable unless it declares size 0 (a demonstrably empty body), a multipart with
    no children is unavailable, a fetched attachment whose decoded length is not the
    declared size is unavailable naming both; the plain-text output is untouched.
T2  `Node.check_ledger` (the repair guard, the chain, the mirror, the anchors) is the
    first ledger read of every path that TRUSTS an existing pending-reply audit — the
    poll's aside count, the pending list / repair / discard verbs — so a forged discard
    record over an anchored completion is a storage failure by the ledger's name with
    nothing deleted and no barrier reached.
T3  Every resumed ledger repair validates the CURRENT mirror as well as the JSONL before
    any cut, marker advance or marker removal: the retained prefix through the recorded
    cut point (an equal-length whitespace replacement is ledger.prose.mismatch naming the
    line, nothing cut, every marker standing); at the audited step the mirror is mended
    while the intent stands and the marker goes only after the mirror verifies.
T4  The stored acks' anchors are checked against the PROPOSED retained chain before any
    cut and again before a repair completes: an entry an authenticated ack anchors is
    never cut as a torn append — a tear inside it is ledger.head.mismatch by name at
    every reader, the repair refuses with nothing written.
T5  The newline matrix: test_gate_round12.py gains the unterminated replacement blank
    last prose line (the audit of the remaining framing cases is in the READY mail).
T6  Every ledger append of the package goes through ONE helper, `Node.ledger_append`,
    which runs `check_ledger` immediately before the line lands; a test pins the call
    sites.

The last section pins the behaviours the round's self-gate reproduced in its progress
messages (an inline Gmail prefix reported complete; the canonical held reply sent and
removed after the ledger check failed; a fresh tail stage and the nested stage cutting
before the current mirror was validated; a blank line after an undecodable one refused
only after the cut; an edited anchored entry terminated before its anchor was checked; a
lost retained prefix regenerated by the nested stage), each fixed before READY; and the
relaunched self-gate's five findings (a child part without a mimeType reported complete; a
found repair audit trusted before the anchored check; the mend at the audited step seeded
from an audit the marker rejects; a whole entry terminated before the mirror was checked;
a CLI assertion that always passed), each fixed before READY.
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

import pytest

from natively.adapters.mail import WIRE_CHARS, MailWire, parse_thread_json
from natively.canon import sha256_hex
from natively.cli import main
from natively.errors import IntegrityError
from natively.ledger import entry_hash
from natively.node import LEDGER_TAIL_MARKER
from natively.objects import new_id

from .test_gate_round6 import _connected_over_mail
from .test_gate_round7 import _argv, _held_ack_over_mail
from .test_gate_round7b import _actions
from .test_gate_round8 import _unseen_mail_ids
from .test_gate_round10 import _tear_mirror, _with_history_over_mail
from .test_gate_round11 import STEPS, _with_ackless_tail_over_mail, _write_marker
from .test_gate_round12 import (
    _mirror_repair_at_truncated,
    _serialize,
    _tail_stage_after_its_audit,
    _torn_audit,
)
from .test_gate_round13 import (
    PKG,
    _b64url,
    _gmail_api,
    _gmail_message,
    _no_markers,
    _unmoved,
    _wire_text,
)

WIRE = "X-Natively: v0\nAAAA\n"


def _never(att):
    pytest.fail(f"nothing to fetch, yet {att} was fetched")


def _unavailable(row: dict, *needles: str) -> None:
    """The row is an INCOMPLETE FETCH: body "", truncated true, the reason naming
    every needle; the adapter reads it so (`RawMail.truncated`, `unavailable`)."""
    assert row["body"] == "" and row["truncated"] is True, row
    for n in needles:
        assert n in row["body_unavailable"], (n, row["body_unavailable"])
    (mail,) = parse_thread_json(json.dumps([row]))
    assert (
        mail.truncated is True and mail.body == "" and mail.unavailable == row["body_unavailable"]
    )


def _complete(row: dict, body: str) -> None:
    assert row["body"] == body and row["truncated"] is False and "body_unavailable" not in row
    (mail,) = parse_thread_json(json.dumps([row]))
    assert mail.truncated is False and mail.unavailable == "" and mail.body == body


# ---- T1. the selected body is demonstrably present (FAILURE BEFORE) --------------------------


def test_a_text_part_without_data_or_attachment_id_is_unavailable_unless_it_declares_size_0():
    """T1 (a), (d): a text/plain part whose body carries neither data nor an
    attachment id is unavailable whatever size it reports — none at all, a positive
    one (as before), a boolean — UNLESS it declares size 0, which is a demonstrably
    empty body: "" complete. The same for a text/html part. The text dump yields ""
    for every shape, as it always did."""
    api = _gmail_api()
    m = _gmail_message("g-nobody", WIRE, inline=False)
    part = m["payload"]["parts"][0]
    part["body"] = {}
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "neither data nor an attachment id")
    assert "undeclared size" in api.msg_row(m, WIRE_CHARS, _never)["body_unavailable"]
    part["body"] = {"size": 200}
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "neither data nor an attachment id", "200")
    part["body"] = {"size": True}  # a boolean is not a size
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "neither data nor an attachment id")
    part["body"] = {"size": "0"}  # a string is not a size either
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "neither data nor an attachment id")
    part["body"] = {"size": 0}
    _complete(api.msg_row(m, WIRE_CHARS, _never), "")
    # an html-only message: the html part is a text part too
    part["mimeType"] = "text/html"
    part["body"] = {}
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "text/html", "neither data")
    part["body"] = {"size": 0}
    _complete(api.msg_row(m, WIRE_CHARS, _never), "")
    part["mimeType"] = "text/plain"
    for body in ({}, {"size": 200}, {"size": 0}, {"size": True}):
        part["body"] = body
        assert api.body_of(m["payload"]) == ""  # the text dump: never a fetch, never a raise


def test_a_multipart_without_children_is_unavailable_never_an_empty_complete_body():
    """T1 (b): a multipart payload with no parts at all (the key absent, or an empty
    list), a nested multipart without children, and a payload with no mimeType are
    unavailable in the --json rows — never body "" complete. A multipart whose
    children hold no text part at all stays what it was: no body, complete (the
    reader judges it). The text dump yields "" for every shape."""
    api = _gmail_api()
    m = _gmail_message("g-noparts", WIRE, inline=True)
    del m["payload"]["parts"]
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "multipart/mixed", "carries no parts")
    assert api.body_of(m["payload"]) == ""
    m["payload"]["parts"] = []
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "carries no parts")
    m["payload"]["parts"] = [
        {"partId": "0", "mimeType": "multipart/alternative", "body": {"size": 0}}
    ]
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "multipart/alternative", "carries no parts")
    assert api.body_of(m["payload"]) == ""
    m["payload"] = {"headers": m["payload"]["headers"]}
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "the payload part", "missing mimeType")
    assert api.body_of(m["payload"]) == ""
    del m["payload"]
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "the payload part", "missing mimeType")
    # children that are not text parts: no body, complete, as before
    png = {
        "partId": "0",
        "mimeType": "image/png",
        "filename": "x.png",
        "body": {"size": 9, "attachmentId": "att-x"},
    }
    m2 = _gmail_message("g-png", WIRE, inline=True)
    m2["payload"]["parts"] = [png]
    _complete(api.msg_row(m2, WIRE_CHARS, _never), "")
    assert api.body_of(m2["payload"]) == ""


def test_a_fetched_attachment_that_is_not_its_declared_size_is_unavailable_naming_both():
    """T1 (c): the attachment fetch returns a valid-base64 PREFIX of the declared
    bytes (18 of 20): unavailable naming the attachment and both sizes; more bytes
    than declared likewise; no declared size to check against likewise; exactly the
    declared bytes: complete."""
    api = _gmail_api()
    m = _gmail_message("g-short", WIRE, inline=False)
    att = "ANGjdJ8_att_g-short"
    declared = len(WIRE.encode("utf-8"))
    assert m["payload"]["parts"][0]["body"]["size"] == declared == 20
    row = api.msg_row(m, WIRE_CHARS, lambda a: _b64url(WIRE[:18]))
    _unavailable(row, att, "declared 20, got 18")
    row = api.msg_row(m, WIRE_CHARS, lambda a: _b64url(WIRE + "xx"))
    _unavailable(row, att, "declared 20, got 22")
    m["payload"]["parts"][0]["body"] = {"attachmentId": att}
    row = api.msg_row(m, WIRE_CHARS, lambda a: _b64url(WIRE))
    _unavailable(row, att, "declares no size", "20 bytes fetched")
    m["payload"]["parts"][0]["body"] = {"attachmentId": att, "size": declared}
    _complete(api.msg_row(m, WIRE_CHARS, lambda a: _b64url(WIRE)), WIRE.strip())
    assert api.body_of(m["payload"]) == ""  # the text dump never fetches


def test_a_short_attachment_leaves_the_mail_unseen_and_the_whole_one_applies(tmp_path):
    """T1, the adapter unchanged: a row the helper reports unavailable (the short
    prefix) leaves the mail unseen, ledgers nothing, counts an incomplete fetch and
    moves neither the freshness clock nor the cursor; the helper returning the whole
    body next poll, the same mail applies."""
    api = _gmail_api()
    a, b, wa, wb, fake, clock = _connected_over_mail(tmp_path)
    wire = _wire_text(a, b, "whole")
    m = _gmail_message("g-prefix", wire, inline=False)
    short = api.msg_row(m, WIRE_CHARS, lambda att: _b64url(wire[: len(wire) - 7]))
    _unavailable(short, "att_g-prefix", f"declared {len(wire.encode())}, got")
    fake.inbox.setdefault("taylor@teale.com", []).append(short)
    before, entries = _unmoved(b, wb), len(b.ledger.entries())
    s = wb.poll_once()
    assert s["applied"] == 0 and s["complete"] is False and s["storage_failures"] == 0
    assert any("could not be obtained" in x and "g-prefix" in x for x in s["errors"])
    assert _unmoved(b, wb) == before and len(b.ledger.entries()) == entries
    assert _unseen_mail_ids(fake, b, wb) == {"g-prefix"}
    fake.inbox["taylor@teale.com"][-1] = api.msg_row(m, WIRE_CHARS, lambda att: _b64url(wire))
    s = wb.poll_once()
    assert s["applied"] == 1 and s["complete"] is True
    assert b.ledger.entries()[-1]["detail"] == "whole"


# ---- T2. a pending audit is trusted only after the anchored check (ORDERING) ----------------


def _aside_without_its_audit(tmp_path, monkeypatch):
    """A held ack corrupted and moved aside on a poll whose corruption audit could
    not be appended (the durable line writer failing for that line): the aside copy
    stands with no audit on record, and b's LAST ledger entry is the completion the
    stored ack for that message anchors. The canonical held reply is held again by
    hand from the stored ack, so both files a discard would remove are present."""
    import natively.ledger as ledgermod

    a, b, wa, wb, fake, clock, held, reports = _held_ack_over_mail(tmp_path, n=1)
    (p,) = held
    msg_id, _ = MailWire.parse_held_name(p.name)
    p.write_bytes(b"{")
    real = ledgermod.append_line

    def append_line(path, line):
        if "pending_reply.corrupt" in line:
            raise OSError(5, "Input/output error")
        return real(path, line)

    monkeypatch.setattr(ledgermod, "append_line", append_line)
    s = wb.poll_once()
    monkeypatch.undo()
    assert s["storage_failures"] >= 1 and s["complete"] is False
    (aside,) = wb._aside_replies()
    assert wb._unresolved(aside) and _actions(b).count("pending_reply.corrupt") == 0
    last = b.ledger.entries()[-1]
    assert last["msg_id"] == msg_id and last["direction"] == "in"
    assert b._seen()[msg_id]["ack"]["ledger_entry"] == entry_hash(last)
    r, why = b.stored_reply(msg_id)
    assert r is not None and why is None
    canonical = wb._hold_reply(r, msg_id)
    assert canonical.exists() and canonical.name == f"{msg_id}.ack.json"
    return a, b, wa, wb, fake, clock, aside, canonical, msg_id


def _forge_discard_record(b, wb, aside: Path) -> None:
    """The anchored last completion edited into a discard record for the aside copy
    (its incoming chain link intact, so the loader alone reads it as the decision to
    remove both files) and its mirror line removed (the documented trailing gap)."""
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    lines = jsonl.read_bytes().split(b"\n")[:-1]
    e = json.loads(lines[-1])
    forged = {
        **e,
        "action": "pending_reply.discarded",
        "grant_id": None,
        "params_hash": None,
        "outcome": "recorded",
        "direction": "out",
        "detail": (
            f"operator discarded the aside held reply {aside.name} "
            f"{wb._audit_key(aside.name)} {MailWire.DROPS_HELD}"
        ),
    }
    jsonl.write_bytes(b"\n".join([*lines[:-1], _serialize(forged)]) + b"\n")
    mirror.write_bytes(b"".join(mirror.read_bytes().splitlines(keepends=True)[:-1]))
    assert b.ledger.entries()[-1]["action"] == "pending_reply.discarded"  # the loader alone
    assert b.ledger._prose_gap(b.ledger.entries(), "x")[0]  # the mirror alone: a gap


@pytest.mark.parametrize("finish", ["discard", "repair"])
def test_a_forged_discard_record_over_an_anchored_completion_deletes_nothing(
    tmp_path, monkeypatch, capsys, finish
):
    """T2: the anchored last completion edited into a matching discard record with
    its mirror line removed. `pending repair`, `pending discard` (with and without
    --with-held), `pending list` and the poll's aside count all refuse by the
    ledger's own name (ledger.head.mismatch naming the msg_id) — a storage failure
    of the verb or the poll: nothing deleted, the aside copy and the canonical held
    reply byte-identical, no ledger barrier reached, nothing appended. Restored, the
    verb completes (the discard from a fresh record; the repair from the stored ack)."""
    a, b, wa, wb, fake, clock, aside, canonical, msg_id = _aside_without_its_audit(
        tmp_path, monkeypatch
    )
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole, prose = jsonl.read_bytes(), mirror.read_bytes()
    _forge_discard_record(b, wb, aside)
    with pytest.raises(IntegrityError) as e:
        b.ledger.check_intact()
    assert e.value.reason == "ledger.head.mismatch" and msg_id in str(e.value)
    files = [jsonl, mirror, aside, canonical, b.state / "seen.json"]
    before = {p: p.read_bytes() for p in files}
    barriers: list[str] = []
    monkeypatch.setattr(b.ledger, "barrier", lambda: barriers.append("barrier"))
    # the verb through the adapter
    s = wb.repair_pending()
    assert s["discarded"] == [] and s["rebuilt"] == [] and s["storage_failures"] == 1
    assert any("ledger.head.mismatch" in x and msg_id in x for x in s["errors"])
    assert {p: p.read_bytes() for p in files} == before and barriers == []
    # the verbs through the CLI
    assert main([*_argv(b), "pending", "repair"]) == 1  # a summary verb: the failure is counted
    out, err = capsys.readouterr()
    assert "ledger.head.mismatch" in err and msg_id in err, err
    assert "1 storage failure(s)" in out and "0 rebuilt" in out and "0 discard(s)" in out, out
    for argv in (
        ["pending", "discard", aside.name],
        ["pending", "discard", aside.name, "--with-held"],
        ["pending", "list"],
    ):
        assert main([*_argv(b), *argv]) == 2, argv
        err = capsys.readouterr().err
        assert "ledger.head.mismatch" in err and msg_id in err, argv
        assert {p: p.read_bytes() for p in files} == before and barriers == []
    # the poll's aside count (the send of the canonical held reply held back by the transport)
    fake.fail_sends = True
    s = wb.poll_once()
    fake.fail_sends = False
    assert s["storage_failures"] >= 1 and s["complete"] is False
    assert any("ledger.head.mismatch" in x and msg_id in x for x in s["errors"])
    assert {p: p.read_bytes() for p in files} == before and barriers == []
    assert "pending_reply" not in jsonl.read_bytes().decode()[len(whole) :]
    monkeypatch.undo()
    # restored: the verb completes
    jsonl.write_bytes(whole)
    mirror.write_bytes(prose)
    assert main([*_argv(b), "ledger", "verify"]) == 0
    if finish == "discard":
        assert main([*_argv(b), "pending", "discard", aside.name, "--with-held"]) == 0
        assert "discarded" in capsys.readouterr().out
        assert not aside.exists() and not canonical.exists()
        assert _actions(b).count("pending_reply.discarded") == 1
        assert b.ledger.entries()[-1]["direction"] == "out"
    else:
        s = wb.repair_pending()
        assert s["rebuilt"] == [aside.name] and s["storage_failures"] == 0
        assert not aside.exists() and aside.with_name(aside.name + ".reconstructed").exists()
        assert canonical.exists() and canonical.read_bytes() == before[canonical]
        assert _actions(b).count("pending_reply.corrupt") == 1
        assert _actions(b).count("pending_reply.reconstructed") == 1
    assert main([*_argv(b), "ledger", "verify"]) == 0


def test_the_anchored_check_is_the_first_ledger_read_of_every_pending_lookup(tmp_path, monkeypatch):
    """T2, ORDERING: `Node.check_ledger` runs inside `_find_pending_entry` before the
    entries are read, for every action the adapter looks up."""
    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    order: list[str] = []
    real_check, real_entries = b.check_ledger, b.ledger.entries
    monkeypatch.setattr(b, "check_ledger", lambda: (order.append("check"), real_check())[1])
    monkeypatch.setattr(b.ledger, "entries", lambda: (order.append("entries"), real_entries())[1])
    for action in (
        "pending_reply.discarded",
        "pending_reply.reconstructed",
        "pending_reply.corrupt",
    ):
        order.clear()
        assert wb._find_pending_entry(action, "x.ack.json.corrupt-1-2") is None
        assert order and order[0] == "check" and "entries" in order
    monkeypatch.setattr(
        b, "check_ledger", lambda: (_ for _ in ()).throw(IntegrityError("ledger.chain", "x"))
    )
    order.clear()
    with pytest.raises(IntegrityError):
        wb._find_pending_entry("pending_reply.discarded", "x")
    assert "entries" not in order


# ---- T3. a resumed repair validates the CURRENT mirror before any mutation ------------------


@pytest.mark.parametrize("how", ["lines-blank", "all-spaces"], ids=["lines-blank", "all-spaces"])
@pytest.mark.parametrize("step", STEPS)
def test_a_resumed_mirror_repair_validates_the_retained_prose_before_any_cut(
    tmp_path, capsys, step, how
):
    """T3 (a): a standing mirror intent at each step, and the prose prefix the intent
    retains replaced by whitespace of EQUAL length (every line blank with its
    newline kept, so the recorded suffix hash still matches; or all spaces): the
    resume is ledger.prose.mismatch naming the line (or the cut point), nothing cut,
    the marker standing at its step, both files and the marker byte-identical, no
    audit added. The prefix restored, the resume completes with exactly one audit."""
    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    _tear_mirror(mirror, "tail")
    tail = b.ledger.excess_prose()
    size = mirror.stat().st_size
    intent = {
        "step": "intent",
        "file": "ledger.prose.txt",
        "truncate_to": size - len(tail),
        "bytes": len(tail),
        "tail_sha256": "sha256:" + sha256_hex(tail),
        "intent_id": new_id("rpr"),
        "ts": b.ts(),
    }
    if step != "intent":
        mirror.write_bytes(mirror.read_bytes()[: intent["truncate_to"]])
        intent["step"] = "truncated"
    if step == "audited":
        audit = b.ledger.append(
            ts=b.ts(),
            actor="solo",
            grant_id=None,
            action="ledger.mirror_truncated",
            params_hash=intent["tail_sha256"],
            outcome="recorded",
            detail=f"truncated {len(tail)} bytes; intent {intent['intent_id']}",
            intent_id=intent["intent_id"],
        )
        intent = {**intent, "step": "audited", "audit_hash": entry_hash(audit)}
    marker = _write_marker(b, intent)
    data, to = mirror.read_bytes(), intent["truncate_to"]
    assert to > 0 and data[:to].endswith(b"\n")
    if how == "lines-blank":
        blank = bytes(0x0A if c == 0x0A else 0x20 for c in data[:to])
    else:
        blank = b" " * to
    mirror.write_bytes(blank + data[to:])
    audits = _actions(b).count("ledger.mirror_truncated") if step == "audited" else 0
    before = (jsonl.read_bytes(), mirror.read_bytes(), marker.read_bytes())
    with pytest.raises(IntegrityError) as e:
        b.ledger.check_prose_prefix(to, b.ledger.check())
    assert e.value.reason == "ledger.prose.mismatch" and str(mirror) in str(e.value)
    assert ("prose line 0" if how == "lines-blank" else "cut point") in str(e.value)
    assert main([*_argv(b), "ledger", "repair"]) == 2
    err = capsys.readouterr().err
    assert "ledger.prose.mismatch" in err and str(mirror) in err
    assert "intent_mismatch" not in err and "truncated" not in capsys.readouterr().out
    assert (jsonl.read_bytes(), mirror.read_bytes(), marker.read_bytes()) == before
    assert json.loads(marker.read_text())["step"] == step
    assert jsonl.read_bytes().count(b"ledger.mirror_truncated") == audits
    # the prefix restored: the resume finishes from its step, one audit in all
    mirror.write_bytes(data)
    assert main([*_argv(b), "ledger", "repair"]) == 0
    assert _no_markers(b) and _actions(b).count("ledger.mirror_truncated") == 1
    assert main([*_argv(b), "ledger", "verify"]) == 0
    wa.send(a.compose_info(b.card, "after"))
    assert wb.poll_once()["applied"] == 1


def _audited_stage(tmp_path, stage: str):
    """A ledger repair marker at step "audited" — the ledger's own tail marker, the
    nested tail marker under a standing mirror intent, or the mirror marker — with
    the stage's audit appended in full (the JSONL line and its prose line landed).
    Returns (b, the intent, its marker, the expected audit counts)."""
    if stage == "mirror":
        a, b, wa, wb, fake, clock, intent, marker = _mirror_repair_at_truncated(tmp_path)
        b._repair_active = "ledger"
        b.ledger.append(
            ts=b.ts(),
            actor="solo",
            grant_id=None,
            action="ledger.mirror_truncated",
            params_hash=intent["tail_sha256"],
            outcome="recorded",
            detail=f"truncated {intent['bytes']} bytes; intent {intent['intent_id']}",
            intent_id=intent["intent_id"],
        )
        b._repair_active = None
        counts = {"ledger.tail_truncated": 0, "ledger.mirror_truncated": 1}
    else:
        b, intent, marker, _mirror_marker = _tail_stage_after_its_audit(
            tmp_path, nested=stage == "nested"
        )
        counts = {"ledger.tail_truncated": 1, "ledger.mirror_truncated": int(stage == "nested")}
    intent = {**intent, "step": "audited", "audit_hash": entry_hash(b.ledger.entries()[-1])}
    marker.write_text(json.dumps(intent), encoding="utf-8")
    assert b.ledger.verify()
    return b, intent, marker, counts


STAGE_IDS = ["own", "nested", "mirror"]


@pytest.mark.parametrize("stage", STAGE_IDS)
def test_an_audited_marker_over_a_strict_prefix_partial_line_is_mended_then_removed(
    tmp_path, capsys, stage
):
    """T3 (b): the marker at "audited" and the mirror's last line — the audit's
    own — torn after 20 ASCII bytes: the resume mends it WHILE the intent stands,
    then removes the marker; verify exits 0, the mirror is whole, exactly the
    stage's audits, a second repair is idempotent."""
    b, intent, marker, counts = _audited_stage(tmp_path, stage)
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole, prose = jsonl.read_bytes(), mirror.read_bytes()
    lines = prose.split(b"\n")[:-1]
    mirror.write_bytes(b"\n".join(lines[:-1]) + b"\n" + lines[-1][:20])
    assert main([*_argv(b), "ledger", "repair"]) == 0
    out, err = capsys.readouterr()
    assert "repaired" in out and "regenerated" in err and "audited step" in err
    # (the nested case: the mirror repair that follows appends its own audit line)
    assert _no_markers(b) and mirror.read_bytes().startswith(prose)
    assert mirror.read_bytes().count(b"\n") == prose.count(b"\n") + int(stage == "nested")
    assert main([*_argv(b), "ledger", "verify"]) == 0
    for action, n in counts.items():
        assert _actions(b).count(action) == n, action
    assert main([*_argv(b), "ledger", "repair"]) == 0
    for action, n in counts.items():
        assert _actions(b).count(action) == n, action
    assert jsonl.read_bytes().startswith(whole)


@pytest.mark.parametrize("stage", STAGE_IDS)
def test_a_non_prefix_partial_line_at_the_audited_step_keeps_the_intent_for_the_retry(
    tmp_path, capsys, stage
):
    """T3 (b): the same marker at "audited", the mirror's last line replaced by bytes
    that are not a prefix of the audit's line (or blank): refused by name
    (ledger.prose.mismatch), the intent standing, every file byte-identical; the
    retry refuses the same way (no double audit); the partial line put back, the
    resume mends and completes."""
    b, intent, marker, counts = _audited_stage(tmp_path, stage)
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole, prose = jsonl.read_bytes(), mirror.read_bytes()
    head = b"".join(prose.splitlines(keepends=True)[:-1])
    markers = {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")}
    assert marker in markers
    for bad in (head + b"zzz", head + b"2026-09-07T07:00:00Z  nobody:", head + b"\xc2\xa0\xc2\xa0"):
        mirror.write_bytes(bad)
        for _retry in range(2):
            assert main([*_argv(b), "ledger", "repair"]) == 2
            err = capsys.readouterr().err
            assert "ledger.prose.mismatch" in err and str(mirror) in err
            assert mirror.read_bytes() == bad and jsonl.read_bytes() == whole
            assert {
                p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")
            } == markers
    mirror.write_bytes(head + prose.splitlines(keepends=True)[-1][:20])
    assert main([*_argv(b), "ledger", "repair"]) == 0
    capsys.readouterr()
    assert _no_markers(b) and main([*_argv(b), "ledger", "verify"]) == 0
    for action, n in counts.items():
        assert _actions(b).count(action) == n, action


def test_the_mirror_check_reads_the_current_mirror_against_the_entries_it_corresponds_to(tmp_path):
    """T3, the method: `check_mirror` accepts a whole mirror, one short by trailing
    lines, one ending in a whole line short of its newline, and one ending in a
    strict prefix; refuses a mismatching line, a blank last line, a non-prefix
    partial, a line beyond the entries (unless the stage cuts excess, in which
    case a blank excess line is still refused), and an undecodable line beyond the
    entries; a mirror torn inside a multibyte character within the entries passes
    (the stage's cut regenerates it)."""
    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    es, mirror = b.ledger.entries(), b.ledger.prose_path
    whole = mirror.read_bytes()
    lines = whole.split(b"\n")[:-1]
    for ok in (
        whole,
        b"\n".join(lines[:-1]) + b"\n",
        whole[:-1],
        b"\n".join(lines[:-1]) + b"\n" + lines[-1][:20],
        b"",
    ):
        mirror.write_bytes(ok)
        b.ledger.check_mirror(es, excess_ok=False)
        b.ledger.check_mirror(es, excess_ok=True)
    mismatch, refused = "ledger.prose.mismatch", "ledger.repair.refused"
    for bad, no_excess, with_excess in (
        # (the mirror, the name under a stage that cuts no excess, under one that does:
        #  None = accepted there, the excess being that stage's cut)
        (b"\n".join([lines[0], b" " * len(lines[1]), lines[2]]) + b"\n", mismatch, mismatch),
        (b"\n".join(lines[:-1]) + b"\n" + b"\xc2\xa0\xc2\xa0", mismatch, mismatch),
        (b"\n".join(lines[:-1]) + b"\n" + b"zzz", mismatch, mismatch),
        (whole + lines[0] + b"\n", mismatch, None),
        (whole + b"   \n", mismatch, refused),
        (whole + b"   ", mismatch, refused),
        (whole + b"\xff\n", mismatch, None),
    ):
        mirror.write_bytes(bad)
        with pytest.raises(IntegrityError) as e:
            b.ledger.check_mirror(es, excess_ok=False)
        assert e.value.reason == no_excess, bad
        if with_excess is None:
            b.ledger.check_mirror(es, excess_ok=True)  # the excess the own tail stage cuts
        else:
            with pytest.raises(IntegrityError) as e:
                b.ledger.check_mirror(es, excess_ok=True)
            assert e.value.reason == with_excess, bad
    mirror.write_bytes(whole)
    _tear_mirror(mirror, "tail")
    b.ledger.check_mirror(es, excess_ok=False)  # a torn regeneration inside the entries
    b.ledger.check_mirror(es, excess_ok=True)
    mirror.write_bytes(whole)
    with pytest.raises(IntegrityError) as e:
        b.ledger.check_prose_prefix(len(whole) + 1, es)
    assert e.value.reason == "ledger.prose.mismatch" and "shorter" in str(e.value)
    with pytest.raises(IntegrityError) as e:
        b.ledger.check_prose_prefix(len(lines[0]) // 2, es)
    assert e.value.reason == "ledger.prose.mismatch" and "cut point" in str(e.value)
    b.ledger.check_prose_prefix(len(lines[0]) + 1, es)
    b.ledger.check_prose_prefix(0, es)


# ---- T4. an anchored entry is never cut (FAILURE BEFORE, RESTART RECOVERY) ------------------


def test_a_tear_inside_an_anchored_completion_is_never_cut_as_a_torn_append(tmp_path, capsys):
    """T4: the last completion — anchored by the ack this node stored for it — torn
    to 50 bytes. Every reader names ledger.head.mismatch with the msg_id (the torn
    tail is never named): the method, check_intact, the verify verb; the repair
    verb refuses by that name with nothing cut, the prose untouched, no audit, no
    marker; the receive is a storage failure by that name, the mail unseen. The
    JSONL restored, verify exits 0 and the waiting mail applies."""
    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole, prose = jsonl.read_bytes(), mirror.read_bytes()
    last = b.ledger.entries()[-1]
    msg_id = last["msg_id"]
    assert b._seen()[msg_id]["ack"]["ledger_entry"] == entry_hash(last)
    lines = whole.split(b"\n")[:-1]
    start = len(whole) - len(lines[-1]) - 1
    jsonl.write_bytes(whole[: start + 50])
    for read in (b.ledger.torn_tail, b.ledger.chain_now, b.ledger.check_intact, b.ledger.verify):
        with pytest.raises(IntegrityError) as e:
            read()
        assert e.value.reason == "ledger.head.mismatch" and msg_id in str(e.value), read
    torn = jsonl.read_bytes()
    assert main([*_argv(b), "ledger", "verify"]) == 2
    err = capsys.readouterr().err
    assert "ledger.head.mismatch" in err and msg_id in err and "ledger.truncated" not in err
    assert main([*_argv(b), "ledger", "repair"]) == 2
    out, err = capsys.readouterr()
    assert "ledger.head.mismatch" in err and msg_id in err and "ledger.truncated" not in err
    assert "truncated" not in out and "terminated" not in out
    assert jsonl.read_bytes() == torn and mirror.read_bytes() == prose and _no_markers(b)
    assert b"ledger.tail_truncated" not in jsonl.read_bytes()
    wa.send(a.compose_info(b.card, "after"))
    s = wb.poll_once()
    assert s["storage_failures"] == 1 and s["applied"] == 0 and s["complete"] is False
    assert any("ledger.head.mismatch" in x and msg_id in x for x in s["errors"])
    assert len(_unseen_mail_ids(fake, b, wb)) == 1
    assert jsonl.read_bytes() == torn and mirror.read_bytes() == prose
    jsonl.write_bytes(whole)
    assert main([*_argv(b), "ledger", "verify"]) == 0
    assert main([*_argv(b), "ledger", "repair"]) == 0 and _no_markers(b)
    assert _actions(b).count("ledger.tail_truncated") == 0
    assert wb.poll_once()["applied"] == 1


def test_the_same_tear_on_an_entry_no_ack_anchors_is_repaired_as_before(tmp_path, capsys):
    """T4: the last entry a revocation.received that no stored ack anchors, torn to 50
    bytes: ledger.truncated at every reader, the repair cuts it and audits once,
    verify exits 0."""
    a, b, wa, wb, fake, clock = _with_ackless_tail_over_mail(tmp_path)
    jsonl = b.ledger.path
    whole = jsonl.read_bytes()
    lines = whole.split(b"\n")[:-1]
    start = len(whole) - len(lines[-1]) - 1
    jsonl.write_bytes(whole[: start + 50])
    assert b.ledger.torn_tail() == whole[start : start + 50]
    with pytest.raises(IntegrityError) as e:
        b.ledger.check_intact()
    assert e.value.reason == "ledger.truncated"
    assert main([*_argv(b), "ledger", "repair"]) == 0
    assert "50 torn byte(s) of the JSONL's last line truncated" in capsys.readouterr().out
    assert _actions(b).count("ledger.tail_truncated") == 1 and _no_markers(b)
    assert main([*_argv(b), "ledger", "verify"]) == 0
    assert jsonl.read_bytes().startswith(whole[:start])


@pytest.mark.parametrize("stage", ["mirror", "nested"])
def test_the_anchor_check_runs_in_the_mirror_stage_and_the_nested_tail_stage(
    tmp_path, capsys, stage
):
    """T4: a standing mirror intent (at "intent": the torn mirror tail still there),
    or the nested tail stage (the mirror repair's audit torn off the JSONL), with
    the anchored last completion EDITED in the JSONL: the resume refuses by name
    (ledger.head.mismatch naming the msg_id) before any cut — both files and every
    marker byte-identical; the entry restored, the resume completes."""
    if stage == "mirror":
        a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
        mirror = b.ledger.prose_path
        _tear_mirror(mirror, "tail")
        tail = b.ledger.excess_prose()
        size = mirror.stat().st_size
        intent = {
            "step": "intent",
            "file": "ledger.prose.txt",
            "truncate_to": size - len(tail),
            "bytes": len(tail),
            "tail_sha256": "sha256:" + sha256_hex(tail),
            "intent_id": new_id("rpr"),
            "ts": b.ts(),
        }
        _write_marker(b, intent)
    else:
        a, b, wa, wb, fake, clock, intent, marker = _mirror_repair_at_truncated(tmp_path)
        _torn_audit(b, intent, "inside")
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole = jsonl.read_bytes()
    lines = whole.split(b"\n")
    # the last WHOLE entry: before the empty element of a terminated file, or before the
    # torn partial line of the nested case
    i = len(lines) - 2
    e = json.loads(lines[i])
    msg_id = e["msg_id"]
    assert b._seen()[msg_id]["ack"]["ledger_entry"] == entry_hash(e)
    lines[i] = _serialize({**e, "detail": e["detail"] + " (edited)"})
    jsonl.write_bytes(b"\n".join(lines))
    markers = {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")}
    assert markers
    before = (jsonl.read_bytes(), mirror.read_bytes())
    assert main([*_argv(b), "ledger", "repair"]) == 2
    out, err = capsys.readouterr()
    assert "ledger.head.mismatch" in err and msg_id in err and "truncated" not in out
    assert (jsonl.read_bytes(), mirror.read_bytes()) == before
    assert {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")} == markers
    assert not (b.state / LEDGER_TAIL_MARKER).exists()
    jsonl.write_bytes(whole)
    assert main([*_argv(b), "ledger", "repair"]) == 0
    assert _no_markers(b) and main([*_argv(b), "ledger", "verify"]) == 0
    assert _actions(b).count("ledger.mirror_truncated") == 1
    assert _actions(b).count("ledger.tail_truncated") == int(stage == "nested")


def test_check_and_check_prefix_are_anchored(tmp_path):
    """T4, the methods: `check`, `check_prefix` and `chain_now` refuse a chain an
    authenticated stored ack no longer anchors into (the last completion edited)
    by name; `repair` and `excess_prose` stand on the same read; a node without
    stored acks is unchanged."""
    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    jsonl = b.ledger.path
    whole = jsonl.read_bytes()
    lines = whole.split(b"\n")[:-1]
    e = json.loads(lines[-1])
    lines[-1] = _serialize({**e, "detail": e["detail"] + " (edited)"})
    jsonl.write_bytes(b"\n".join(lines) + b"\n")
    b.ledger.entries()  # the loader alone passes
    for read in (
        b.ledger.check,
        lambda: b.ledger.check_prefix(len(jsonl.read_bytes())),
        b.ledger.chain_now,
        b.ledger.repair,
        b.ledger.excess_prose,
        b.ledger.torn_tail,
    ):
        with pytest.raises(IntegrityError) as ex:
            read()
        assert ex.value.reason == "ledger.head.mismatch", read
    jsonl.write_bytes(whole)
    assert b.ledger.check() == b.ledger.entries() and b.ledger.chain_now()[1] == b""
    from .conftest import Clock, make_node

    n = make_node(tmp_path, "solo", Clock())
    n.receive(n.compose_card())
    assert n.ledger.check() and n.ledger.chain_now()[1] == b"" and n.ledger.repair() == 0


# ---- T6. every ledger append goes through the one checked helper (ORDERING) -----------------


def _append_sites(tree: ast.AST) -> set[str]:
    """The enclosing function of every `<...>.ledger.append(...)` / `Ledger.append(...)`
    call in a module."""
    out: set[str] = set()
    for fn in ast.walk(tree):
        if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for node in ast.walk(fn):
            if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)):
                continue
            if node.func.attr != "append":
                continue
            v = node.func.value
            if (isinstance(v, ast.Attribute) and v.attr == "ledger") or (
                isinstance(v, ast.Name) and v.id in ("Ledger", "ledger")
            ):
                out.add(fn.name)
    return out


def test_every_ledger_append_in_the_package_goes_through_the_node_helper():
    """T6: the only `Ledger.append` call site in the package is `Node.ledger_append`,
    whose first statement is `check_ledger` (the repair guard plus the full check
    with its anchors) — the receive's completions, the verbs' records, the repair
    audits, the outbox's undelivered line, the replayed revocation, the adapter's
    lines all go through it."""
    found: set[tuple[str, str]] = set()
    for f in sorted((PKG / "natively").rglob("*.py")):
        rel = f.relative_to(PKG).as_posix()
        for fn in _append_sites(ast.parse(f.read_text(encoding="utf-8"))):
            found.add((rel, fn))
    assert found == {("natively/node.py", "ledger_append")}
    tree = ast.parse((PKG / "natively" / "node.py").read_text(encoding="utf-8"))
    (helper,) = [
        n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef) and n.name == "ledger_append"
    ]
    body = [
        s
        for s in helper.body
        if not isinstance(s, ast.Expr) or not isinstance(s.value, ast.Constant)
    ]
    first = body[0]
    assert isinstance(first, ast.Expr) and isinstance(first.value, ast.Call)
    assert ast.unparse(first.value.func) == "self.check_ledger"
    assert (
        isinstance(body[1], ast.Return) and ast.unparse(body[1].value.func) == "self.ledger.append"
    )
    assert len(body) == 2


def test_the_five_sites_append_only_over_a_ledger_that_passes_its_check(tmp_path, monkeypatch):
    """T6, the Fable read's five sites: the revoke verb, the deny verb, the outbox's
    undelivered line, the replay of a held revocation at the pin, and the repair
    audit — each refuses by the ledger's own name (the anchored last completion
    edited: ledger.head.mismatch) with nothing appended; the revoke and the deny
    refuse before their enforcing record lands."""
    from natively import revocation as revmod

    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    b.config["extensions"]["standing_denial"] = True
    b.save_config()
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole = jsonl.read_bytes()
    lines = whole.split(b"\n")[:-1]
    e = json.loads(lines[-1])
    lines[-1] = _serialize({**e, "detail": e["detail"] + " (edited)"})
    jsonl.write_bytes(b"\n".join(lines) + b"\n")
    # its mirror line removed too (the documented trailing gap): the chain and the
    # mirror comparison pass, only the anchor catches the edit
    mirror.write_bytes(b"".join(mirror.read_bytes().splitlines(keepends=True)[:-1]))
    feed, store = b.revocations.path, b.denials.path
    feed_before = feed.read_bytes() if feed.exists() else None
    store_before = store.read_bytes() if store.exists() else None
    n = len(jsonl.read_bytes())
    with pytest.raises(IntegrityError) as ex:
        b.revoke(grants=["grt_01AAAAAAAAAAAAAAAAAAAAAAAA"], principal_statement="x")
    assert ex.value.reason == "ledger.head.mismatch"
    with pytest.raises(IntegrityError) as ex:
        b.deny(deny=[{"action": "fs.write", "resource": "x"}], principal_statement="x")
    assert ex.value.reason == "ledger.head.mismatch"
    assert (feed.read_bytes() if feed.exists() else None) == feed_before
    assert (store.read_bytes() if store.exists() else None) == store_before
    # the outbox: a pending send past its last deadline
    wb.send(b.compose_info(a.card, "anyone?"))
    ob = b.outbox()
    assert ob and ob[-1]["status"] == "pending"
    with pytest.raises(IntegrityError) as ex:
        b.outbox_mark_undelivered(ob[-1]["msg_id"])
    assert ex.value.reason == "ledger.head.mismatch"
    assert b.outbox()[-1]["status"] == "pending"
    # the replay of a held revocation at the pin
    assert len(jsonl.read_bytes()) == n
    with pytest.raises(IntegrityError) as ex:
        b.pin(a.principal.public, "again")
    assert ex.value.reason == "ledger.head.mismatch"
    assert len(jsonl.read_bytes()) == n
    assert revmod is not None


# ---- T5. the newline matrix: the unterminated replacement blank last line -------------------
# (test_gate_round12.py test_a_blank_line_in_the_prose_mirror_is_a_mismatch_by_name carries the
# variant; the audit of every remaining framing case is in the READY mail.)


def test_the_round12_blank_last_line_test_carries_the_unterminated_variant():
    """T5: the round-12 test stages the replacement blank last prose line both with
    its newline and without it."""
    src = (PKG / "tests" / "test_gate_round12.py").read_text(encoding="utf-8")
    body = src.split("def test_a_blank_line_in_the_prose_mirror_is_a_mismatch_by_name", 1)[1]
    body = body.split("\ndef ", 1)[0]
    assert 'b"\\n".join([*lines[:-1], BLANK]) + b"\\n"' in body
    assert 'b"\\n".join([*lines[:-1], BLANK]),' in body


# ---- the round's self-gate: the behaviours it reproduced, fixed before READY ------------------


def test_inline_data_that_is_not_the_declared_size_is_unavailable_naming_both():
    """Self-gate, T1 family: the helper reported an INLINE body complete when its
    base64 decoded to a prefix of the declared bytes (the attachment rule did not
    reach inline data). Now inline data shorter or longer than the declared size is
    unavailable naming both sizes; exactly the declared bytes is complete; inline
    data with no declared size (or a boolean for one) is the bytes the API served,
    complete as before; the text dump never checks a size."""
    api = _gmail_api()
    declared = len(WIRE.encode("utf-8"))
    m = _gmail_message("g-inline", WIRE, inline=True)
    part = m["payload"]["parts"][0]
    assert part["body"]["size"] == declared == 20
    part["body"] = {"size": declared, "data": _b64url(WIRE[:16])}
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "inline data", "declared 20, got 16")
    assert api.body_of(m["payload"]) == WIRE[:16]  # the text dump: the bytes served, no check
    part["body"] = {"size": declared, "data": _b64url(WIRE + "xx")}
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "inline data", "declared 20, got 22")
    part["body"] = {"size": declared, "data": _b64url(WIRE)}
    _complete(api.msg_row(m, WIRE_CHARS, _never), WIRE.strip())
    part["body"] = {"data": _b64url(WIRE)}
    _complete(api.msg_row(m, WIRE_CHARS, _never), WIRE.strip())
    part["body"] = {"size": True, "data": _b64url(WIRE[:16])}  # a boolean is not a size
    _complete(api.msg_row(m, WIRE_CHARS, _never), WIRE[:16].strip())


def test_a_short_inline_body_leaves_the_mail_unseen_and_the_whole_one_applies(tmp_path):
    """Self-gate, T1 family, the adapter: an inline prefix of the declared bytes was
    a row with a body — decoded as peer garbage, ledgered wire.decode verify_failed
    and marked seen, the mail consumed on the strength of a partial body. Now the
    row is unavailable: the mail unseen, nothing ledgered, the fetch incomplete,
    the clocks unmoved; the whole body next poll applies."""
    api = _gmail_api()
    a, b, wa, wb, fake, clock = _connected_over_mail(tmp_path)
    wire = _wire_text(a, b, "whole")
    declared = len(wire.encode("utf-8"))
    m = _gmail_message("g-inline-prefix", wire, inline=True)
    m["payload"]["parts"][0]["body"] = {"size": declared, "data": _b64url(wire[: len(wire) - 7])}
    short = api.msg_row(m, WIRE_CHARS, _never)
    _unavailable(short, "inline data", f"declared {declared}, got")
    fake.inbox.setdefault("taylor@teale.com", []).append(short)
    before, entries = _unmoved(b, wb), len(b.ledger.entries())
    s = wb.poll_once()
    assert s["applied"] == 0 and s["complete"] is False and s["storage_failures"] == 0
    assert any("could not be obtained" in x and "g-inline-prefix" in x for x in s["errors"])
    assert _unmoved(b, wb) == before and len(b.ledger.entries()) == entries
    assert _unseen_mail_ids(fake, b, wb) == {"g-inline-prefix"}
    assert "wire.decode" not in _actions(b)
    m["payload"]["parts"][0]["body"] = {"size": declared, "data": _b64url(wire)}
    fake.inbox["taylor@teale.com"][-1] = api.msg_row(m, WIRE_CHARS, _never)
    s = wb.poll_once()
    assert s["applied"] == 1 and s["complete"] is True
    assert b.ledger.entries()[-1]["detail"] == "whole"


def test_a_failing_ledger_check_holds_the_canonical_reply_back_from_the_transport(
    tmp_path, monkeypatch
):
    """Self-gate, T2 family: the poll's aside count refused by name (the anchored
    completion edited into a discard record) and, on the SAME poll, the canonical
    held reply was validated, sent and removed — an ack out over a ledger that
    failed its check, and a file the discard would remove gone. Now the flush runs
    `Node.check_ledger` once, first, when anything is held: one storage failure by
    the ledger's name, no transport call, the held reply and the aside copy
    byte-identical, no barrier; restored, the next poll sends it and removes the
    held copy, the aside copy stays for its verb."""
    a, b, wa, wb, fake, clock, aside, canonical, msg_id = _aside_without_its_audit(
        tmp_path, monkeypatch
    )
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole, prose = jsonl.read_bytes(), mirror.read_bytes()
    _forge_discard_record(b, wb, aside)
    files = [jsonl, mirror, aside, canonical, b.state / "seen.json"]
    before = {p: p.read_bytes() for p in files}
    barriers: list[str] = []
    monkeypatch.setattr(b.ledger, "barrier", lambda: barriers.append("barrier"))
    sends = len(fake.sends)
    s = wb.poll_once()
    assert s["replies"] == 0 and s["complete"] is False and s["storage_failures"] == 1
    (error,) = s["errors"]
    assert "ledger.head.mismatch" in error and msg_id in error
    assert "the ledger before the held replies go out" in error
    assert len(fake.sends) == sends and barriers == []
    assert {p: p.read_bytes() for p in files} == before
    monkeypatch.undo()
    jsonl.write_bytes(whole)
    mirror.write_bytes(prose)
    s = wb.poll_once()
    assert s["replies"] == 1 and len(fake.sends) == sends + 1
    assert not canonical.exists() and aside.exists()
    assert _actions(b).count("pending_reply.corrupt") == 1  # the aside's audit, written now


@pytest.mark.parametrize("stage", ["own", "nested"])
def test_a_fresh_tail_stage_validates_the_current_mirror_before_it_cuts(tmp_path, capsys, stage):
    """Self-gate, T3 family: a FRESH tail stage (no marker of its own) over a mirror
    whose prose line 0 is spaces of equal length: the torn JSONL tail was cut, the
    marker written and advanced to "truncated", and only the audit append refused
    (ledger.prose.mismatch) — a cut before the mirror was validated. Now the fresh
    run validates the current mirror against the chain that remains before its
    intent is written (the ledger's own stage), or the standing mirror intent's
    retained prefix is checked before the subordinate stage runs (the nested one):
    refused by name naming prose line 0, the JSONL with its torn tail, the mirror
    and every standing marker byte-identical, no tail marker, no audit; the line
    restored, the repair completes."""
    if stage == "own":
        a, b, wa, wb, fake, clock = _with_ackless_tail_over_mail(tmp_path)
        jsonl = b.ledger.path
        whole = jsonl.read_bytes()
        lines = whole.split(b"\n")[:-1]
        jsonl.write_bytes(whole[: len(whole) - len(lines[-1]) - 1 + 50])
        audits = {"ledger.tail_truncated": 1, "ledger.mirror_truncated": 0}
    else:
        a, b, wa, wb, fake, clock, intent, marker = _mirror_repair_at_truncated(tmp_path)
        _torn_audit(b, intent, "before")
        jsonl = b.ledger.path
        audits = {"ledger.tail_truncated": 1, "ledger.mirror_truncated": 1}
    mirror = b.ledger.prose_path
    data = mirror.read_bytes()
    first = data.index(b"\n")
    mirror.write_bytes(b" " * first + data[first:])  # line 0 spaces, its newline kept
    markers = {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")}
    assert len(markers) == int(stage == "nested")
    before = (jsonl.read_bytes(), mirror.read_bytes())
    assert main([*_argv(b), "ledger", "repair"]) == 2
    out, err = capsys.readouterr()
    assert "ledger.prose.mismatch" in err and "prose line 0" in err
    assert "truncated" not in out and "terminated" not in out
    assert (jsonl.read_bytes(), mirror.read_bytes()) == before
    assert {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")} == markers
    assert not (b.state / LEDGER_TAIL_MARKER).exists()
    assert b"ledger.tail_truncated" not in jsonl.read_bytes()
    mirror.write_bytes(data)
    assert main([*_argv(b), "ledger", "repair"]) == 0
    assert _no_markers(b) and main([*_argv(b), "ledger", "verify"]) == 0
    for action, n in audits.items():
        assert _actions(b).count(action) == n, action


@pytest.mark.parametrize("marker", ["none", "intent"])
def test_a_blank_line_after_an_undecodable_one_is_refused_before_the_tail_is_cut(
    tmp_path, capsys, marker
):
    """Self-gate, T3 family: the mirror beyond the entries undecodable in one line
    and BLANK in the next, under the ledger's own tail stage: the validation (fresh
    or resumed at "intent") took the damage for the stage's excess, the torn JSONL
    tail was cut and the marker advanced, and only the cut of the excess refused
    (ledger.repair.refused). Now the WHOLE proposed cut is checked at the
    validation: refused by that name with the JSONL uncut, the mirror untouched and
    the marker, where one stands, at its step; the blank line gone, the repair
    completes and the undecodable excess is cut as before."""
    a, b, wa, wb, fake, clock = _with_ackless_tail_over_mail(tmp_path)
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole = jsonl.read_bytes()
    lines = whole.split(b"\n")[:-1]
    start = len(whole) - len(lines[-1]) - 1
    torn = whole[start : start + 50]
    jsonl.write_bytes(whole[: start + 50])
    prose = mirror.read_bytes()
    mirror.write_bytes(prose + b"\xff\n   \n")
    if marker == "intent":
        _write_marker(
            b,
            {
                "step": "intent",
                "file": "ledger.jsonl",
                "truncate_to": start,
                "bytes": 50,
                "tail_sha256": "sha256:" + sha256_hex(torn),
                "intent_id": new_id("rpr"),
                "ts": b.ts(),
            },
        )
    markers = {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")}
    before = (jsonl.read_bytes(), mirror.read_bytes())
    assert main([*_argv(b), "ledger", "repair"]) == 2
    out, err = capsys.readouterr()
    assert "ledger.repair.refused" in err and "is blank" in err and "truncated" not in out
    assert (jsonl.read_bytes(), mirror.read_bytes()) == before
    assert {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")} == markers
    mirror.write_bytes(prose + b"\xff\n")
    assert main([*_argv(b), "ledger", "repair"]) == 0
    assert _no_markers(b) and main([*_argv(b), "ledger", "verify"]) == 0
    assert _actions(b).count("ledger.tail_truncated") == 1
    assert _actions(b).count("ledger.mirror_truncated") == 0


def test_an_anchored_entry_edited_and_left_without_its_newline_is_never_terminated(
    tmp_path, capsys
):
    """Self-gate, T4 family: the anchored last completion EDITED and its newline
    dropped: `terminate_tail` found a whole entry of the chain short of only its
    newline and wrote the newline — one byte into a record its anchor says was
    altered — before the tail stage's anchor check refused. Now the chain the
    newline would complete is anchored first: ledger.head.mismatch, nothing
    written; the repair verb refuses by that name with the JSONL byte-identical and
    no marker. The UNEDITED entry without its newline is still terminated. And the
    file cut inside its FIRST entry — an empty chain before the tear, which anchors
    none of the stored acks — names ledger.head.mismatch at every reader, never
    ledger.truncated."""
    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    jsonl = b.ledger.path
    whole = jsonl.read_bytes()
    lines = whole.split(b"\n")[:-1]
    last = json.loads(lines[-1])
    msg_id = last["msg_id"]
    assert b._seen()[msg_id]["ack"]["ledger_entry"] == entry_hash(last)
    edited = _serialize({**last, "detail": last["detail"] + " (edited)"})
    jsonl.write_bytes(b"\n".join([*lines[:-1], edited]))  # no final newline
    torn = jsonl.read_bytes()
    with pytest.raises(IntegrityError) as e:
        b.ledger.terminate_tail()
    assert e.value.reason == "ledger.head.mismatch" and msg_id in str(e.value)
    assert jsonl.read_bytes() == torn
    assert main([*_argv(b), "ledger", "repair"]) == 2
    out, err = capsys.readouterr()
    assert "ledger.head.mismatch" in err and msg_id in err
    assert "terminated" not in out and "truncated" not in out
    assert jsonl.read_bytes() == torn and _no_markers(b)
    # the unedited entry short of only its newline: terminated as before
    jsonl.write_bytes(whole[:-1])
    assert b.ledger.terminate_tail() is True and jsonl.read_bytes() == whole
    assert main([*_argv(b), "ledger", "verify"]) == 0
    # a tear inside the first entry: the empty chain before it anchors nothing
    jsonl.write_bytes(whole[:50])
    for read in (b.ledger.entries, b.ledger.check_intact, b.ledger.verify, b.ledger.torn_tail):
        b.ledger._entries = None
        with pytest.raises(IntegrityError) as e:
            read()
        assert e.value.reason == "ledger.head.mismatch", read
    assert main([*_argv(b), "ledger", "verify"]) == 2
    err = capsys.readouterr().err
    assert "ledger.head.mismatch" in err and "ledger.truncated" not in err
    jsonl.write_bytes(whole)
    assert main([*_argv(b), "ledger", "verify"]) == 0


@pytest.mark.parametrize("nested", ["fresh", "standing"], ids=["fresh-nested", "standing-nested"])
def test_a_mirror_intent_whose_retained_prefix_is_lost_is_refused_before_the_nested_stage(
    tmp_path, capsys, nested
):
    """Self-gate, T3 family: a mirror intent at step "truncated" whose retained
    prose prefix is GONE (the mirror empty), the JSONL's tail torn (the audit
    append that tore): the subordinate tail stage cut the tail, its audit append
    regenerated every line, and the mirror stage then found its prefix present and
    completed — a lost prefix regenerated by a stage the intent never validated.
    Now the standing intent's retained prefix is checked first, against the chain
    the JSONL holds: ledger.prose.mismatch (shorter than the cut point), nothing
    cut, both files and every marker byte-identical, whether the nested marker
    already stands or the nested stage would be fresh; the prefix restored, the
    resume completes with one audit per stage."""
    a, b, wa, wb, fake, clock, intent, marker = _mirror_repair_at_truncated(tmp_path)
    _torn_audit(b, intent, "before")
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    retained = mirror.read_bytes()
    assert len(retained) == intent["truncate_to"] > 0
    whole = jsonl.read_bytes()
    if nested == "standing":
        keep, sep, torn = whole.rpartition(b"\n")
        (b.state / LEDGER_TAIL_MARKER).write_text(
            json.dumps(
                {
                    "step": "intent",
                    "file": "ledger.jsonl",
                    "truncate_to": len(keep + sep),
                    "bytes": len(torn),
                    "tail_sha256": "sha256:" + sha256_hex(torn),
                    "intent_id": new_id("rpr"),
                    "ts": b.ts(),
                }
            ),
            encoding="utf-8",
        )
    mirror.write_bytes(b"")
    markers = {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")}
    assert len(markers) == (2 if nested == "standing" else 1)
    assert main([*_argv(b), "ledger", "repair"]) == 2
    out, err = capsys.readouterr()
    assert "ledger.prose.mismatch" in err and "shorter than the repair intent's cut point" in err
    assert "truncated" not in out and "terminated" not in out
    assert jsonl.read_bytes() == whole and mirror.read_bytes() == b""
    assert {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")} == markers
    mirror.write_bytes(retained)
    assert main([*_argv(b), "ledger", "repair"]) == 0
    assert _no_markers(b) and main([*_argv(b), "ledger", "verify"]) == 0
    assert _actions(b).count("ledger.tail_truncated") == 1
    assert _actions(b).count("ledger.mirror_truncated") == 1


# ---- the relaunched self-gate (r14b): three MAJOR, two MINOR, each fixed before READY --------


def test_a_child_part_without_a_mimetype_is_unavailable_at_any_depth(tmp_path):
    """r14b finding 1: a multipart payload whose child carries no mimeType (`{"body":
    {"size": 20}}`) was passed over as "not a text part" and the row reported
    complete and empty — ledgered wire.header and marked seen. Now any part without
    a mimeType, at any depth, is unavailable on the --json path naming it (the root
    is named as the payload part); a non-string mimeType likewise; the text dump yields ""
    as before. Through the adapter: the mail unseen, nothing ledgered, the clocks
    unmoved; the mimeType restored, the same mail applies."""
    api = _gmail_api()
    m = _gmail_message("g-nomime", WIRE, inline=True)
    m["payload"]["parts"] = [{"partId": "0", "body": {"size": 20}}]
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "missing mimeType", "partId 0")
    assert api.body_of(m["payload"]) == ""
    m["payload"]["parts"] = [
        {
            "partId": "0",
            "mimeType": "multipart/alternative",
            "body": {"size": 0},
            "parts": [{"partId": "0.0", "body": {"size": 20, "data": _b64url(WIRE)}}],
        }
    ]
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "missing mimeType", "partId 0.0")
    assert api.body_of(m["payload"]) == ""
    m["payload"]["parts"][0]["parts"][0]["mimeType"] = 7
    _unavailable(api.msg_row(m, WIRE_CHARS, _never), "missing mimeType", "partId 0.0")
    m["payload"]["parts"][0]["parts"][0]["mimeType"] = "text/plain"
    _complete(api.msg_row(m, WIRE_CHARS, _never), WIRE.strip())
    # the adapter round trip
    a, b, wa, wb, fake, clock = _connected_over_mail(tmp_path)
    wire = _wire_text(a, b, "whole")
    m = _gmail_message("g-nomime-2", wire, inline=True)
    del m["payload"]["parts"][0]["mimeType"]
    row = api.msg_row(m, WIRE_CHARS, _never)
    _unavailable(row, "missing mimeType")
    fake.inbox.setdefault("taylor@teale.com", []).append(row)
    before, entries = _unmoved(b, wb), len(b.ledger.entries())
    s = wb.poll_once()
    assert s["applied"] == 0 and s["complete"] is False and s["storage_failures"] == 0
    assert any("could not be obtained" in x and "g-nomime-2" in x for x in s["errors"])
    assert _unmoved(b, wb) == before and len(b.ledger.entries()) == entries
    assert _unseen_mail_ids(fake, b, wb) == {"g-nomime-2"}
    m["payload"]["parts"][0]["mimeType"] = "text/plain"
    fake.inbox["taylor@teale.com"][-1] = api.msg_row(m, WIRE_CHARS, _never)
    s = wb.poll_once()
    assert s["applied"] == 1 and s["complete"] is True
    assert b.ledger.entries()[-1]["detail"] == "whole"


def _store_stage_at_truncated_over_a_forged_audit(tmp_path, store: str):
    """b connected to a, its feed (or denial store) written BEFORE its last
    completion — an info a sent, its ack stored, so that completion is anchored —
    and that completion then edited into the `<store>.repaired` record of a
    marker at step "truncated" (the chain link intact, the mirror line removed):
    the loader alone reads the audit as landed. Returns (b, the store path, the
    verb, the audit action, the marker, the anchored msg_id)."""
    a, b, wa, wb, fake, clock = _connected_over_mail(tmp_path)
    if store == "feed":
        b.revoke(grants=["grt_01AAAAAAAAAAAAAAAAAAAAAAAA"], principal_statement="x")
        path, verb, action, fname = b.revocations.path, "feed", "feed.repaired", "revocations.jsonl"
    else:
        b.config["extensions"]["standing_denial"] = True
        b.save_config()
        b.deny(deny=[{"action": "fs.write", "resource": "x"}], principal_statement="x")
        path, verb, action, fname = b.denials.path, "denial", "denial.repaired", "denials.jsonl"
    wa.send(a.compose_info(b.card, "anchored"))
    assert wb.poll_once()["applied"] == 1 and wa.poll_once()["applied"] == 1
    last = b.ledger.entries()[-1]
    msg_id = last["msg_id"]
    assert last["direction"] == "in"
    assert b._seen()[msg_id]["ack"]["ledger_entry"] == entry_hash(last)
    torn = b'{"torn": "' + b"x" * 30
    intent = {
        "step": "truncated",
        "file": fname,
        "truncate_to": path.stat().st_size,
        "bytes": len(torn),
        "tail_sha256": "sha256:" + sha256_hex(torn),
        "intent_id": new_id("rpr"),
        "ts": b.ts(),
    }
    marker = b.state / f"{verb}-repair-pending.json"
    marker.write_text(json.dumps(intent), encoding="utf-8")
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    lines = jsonl.read_bytes().split(b"\n")[:-1]
    forged = {
        **last,
        "action": action,
        "grant_id": None,
        "params_hash": intent["tail_sha256"],
        "outcome": "recorded",
        "direction": "out",
        "detail": (
            f"truncated a torn partial last line ({len(torn)} bytes) of {fname}; "
            f"intent {intent['intent_id']}"
        ),
        "intent_id": intent["intent_id"],  # round 15: the field the lookup matches
    }
    jsonl.write_bytes(b"\n".join([*lines[:-1], _serialize(forged)]) + b"\n")
    mirror.write_bytes(b"".join(mirror.read_bytes().splitlines(keepends=True)[:-1]))
    assert b._repair_audit(verb, action, intent) is not None  # the loader alone
    return b, path, verb, action, marker, msg_id, lines


@pytest.mark.parametrize("store", ["feed", "denial"])
def test_a_found_repair_audit_is_trusted_only_after_the_anchored_check(
    tmp_path, monkeypatch, capsys, store
):
    """r14b finding 2: the anchored last completion edited into this intent's
    `<store>.repaired` record, its mirror line removed, the marker at "truncated".
    Before: the resume found the record, ran the ledger barrier (which regenerated
    the forged prose), promoted the marker to "audited" and only then refused —
    and, restored, stayed stuck at intent_mismatch. Now the ledger's full check
    with its anchors runs first: ledger.head.mismatch naming the msg_id, the
    marker at its step, no barrier, the JSONL, the mirror and the store
    byte-identical; twice. Restored, the resume appends its audit and completes."""
    b, path, verb, action, marker, msg_id, lines = _store_stage_at_truncated_over_a_forged_audit(
        tmp_path, store
    )
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    files = [jsonl, mirror, path, marker]
    before = {p: p.read_bytes() for p in files}
    barriers: list[str] = []
    monkeypatch.setattr(b.ledger, "barrier", lambda: barriers.append("barrier"))
    for _retry in range(2):
        assert main([*_argv(b), verb, "repair"]) == 2
        err = capsys.readouterr().err
        assert "ledger.head.mismatch" in err and msg_id in err, err
        assert {p: p.read_bytes() for p in files} == before and barriers == []
        assert json.loads(marker.read_text())["step"] == "truncated"
    monkeypatch.undo()
    # restored: the completion back in place, its prose regenerated by the resume
    jsonl.write_bytes(b"\n".join(lines) + b"\n")
    assert main([*_argv(b), verb, "repair"]) == 0
    capsys.readouterr()
    assert not marker.exists() and main([*_argv(b), "ledger", "verify"]) == 0
    assert _actions(b).count(action) == 1
    assert b.ledger.entries()[-2]["msg_id"] == msg_id


@pytest.mark.parametrize("stage", STAGE_IDS)
def test_an_edited_last_audit_never_seeds_the_mend_at_the_audited_step(tmp_path, capsys, stage):
    """r14b finding 3: the marker at "audited" recording the audit's hash, the
    last audit EDITED (its actor: the chain still links, nothing follows it) and
    the mirror's last line a strict prefix of the EDITED entry's prose. Before,
    the mend wrote the rest of that line before the hash check refused. Now the
    audit's identity is checked first, read-only: ledger.repair.intent_mismatch
    naming the hashes, the mirror and the JSONL byte-identical, every marker
    standing; twice. The entry restored and the partial line a prefix of its
    prose, the resume mends, completes and verifies."""
    b, intent, marker, counts = _audited_stage(tmp_path, stage)
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole, prose = jsonl.read_bytes(), mirror.read_bytes()
    lines = whole.split(b"\n")[:-1]
    e = json.loads(lines[-1])
    assert e["actor"] == "solo"
    edited = {**e, "actor": "solo-edited"}
    jsonl.write_bytes(b"\n".join([*lines[:-1], _serialize(edited)]) + b"\n")
    from natively.ledger import prose_line

    edited_line = prose_line(edited, entry_hash(edited)).encode("utf-8")
    head = b"".join(prose.splitlines(keepends=True)[:-1])
    partial = head + edited_line[: len(e["ts"]) + 2 + len("solo-ed")]
    assert not prose.splitlines(keepends=True)[-1].startswith(partial[len(head) :])
    mirror.write_bytes(partial)
    torn_jsonl = jsonl.read_bytes()
    markers = {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")}
    assert marker in markers
    for _retry in range(2):
        assert main([*_argv(b), "ledger", "repair"]) == 2
        err = capsys.readouterr().err
        assert "ledger.repair.intent_mismatch" in err and "hashes to" in err, err
        assert mirror.read_bytes() == partial and jsonl.read_bytes() == torn_jsonl
        assert {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")} == markers
    jsonl.write_bytes(whole)
    mirror.write_bytes(head + prose.splitlines(keepends=True)[-1][:20])
    assert main([*_argv(b), "ledger", "repair"]) == 0
    capsys.readouterr()
    assert _no_markers(b) and main([*_argv(b), "ledger", "verify"]) == 0
    for action, n in counts.items():
        assert _actions(b).count(action) == n, action


@pytest.mark.parametrize("damage", ["unterminated", "whole-line"])
def test_a_fresh_repair_terminates_a_whole_entry_only_after_the_mirror_checks(
    tmp_path, capsys, damage
):
    """r14b finding 4, fresh: the JSONL's last entry whole short of only its
    newline, the mirror's last line damaged (replaced by bytes that are not a
    prefix of it, unterminated, or by a whole line that is not it). Before, the
    newline was written and the mirror then refused. Now the mirror is checked
    against the chain the newline would complete first: ledger.prose.mismatch,
    the JSONL byte-identical, no marker; the mirror restored, the entry is
    terminated and verify exits 0."""
    a, b, wa, wb, fake, clock = _with_history_over_mail(tmp_path)
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    whole, prose = jsonl.read_bytes(), mirror.read_bytes()
    jsonl.write_bytes(whole[:-1])
    head = b"".join(prose.splitlines(keepends=True)[:-1])
    bad = head + (b"zzz" if damage == "unterminated" else b"zzz\n")
    mirror.write_bytes(bad)
    for _retry in range(2):
        assert main([*_argv(b), "ledger", "repair"]) == 2
        err = capsys.readouterr().err
        assert "ledger.prose.mismatch" in err and str(mirror) in err, err
        assert jsonl.read_bytes() == whole[:-1] and mirror.read_bytes() == bad
        assert _no_markers(b)
    mirror.write_bytes(prose)
    assert main([*_argv(b), "ledger", "repair"]) == 0
    out, err = capsys.readouterr()
    assert "terminated" in err
    assert jsonl.read_bytes() == whole and _no_markers(b)
    assert main([*_argv(b), "ledger", "verify"]) == 0


def test_a_mirror_intent_terminates_its_audit_only_after_the_mirror_checks(tmp_path, capsys):
    """r14b finding 4, under a standing mirror intent at "truncated": the audit
    entry landed short of only its newline, the retained prefix valid, and a
    non-prefix partial line appended past it. Before, the newline was written and
    the mirror stage then refused. Now: ledger.prose.mismatch before the write,
    the JSONL and the marker byte-identical; twice. The partial line removed, the
    resume terminates the audit, regenerates its line and completes."""
    a, b, wa, wb, fake, clock, intent, marker = _mirror_repair_at_truncated(tmp_path)
    _torn_audit(b, intent, "unterminated")
    jsonl, mirror = b.ledger.path, b.ledger.prose_path
    torn_jsonl, retained = jsonl.read_bytes(), mirror.read_bytes()
    # the mirror: the retained prefix plus the line the completed run regenerated,
    # the audit's own line removed with its newline (`_torn_audit`)
    assert not torn_jsonl.endswith(b"\n") and retained.endswith(b"\n")
    assert len(retained) > intent["truncate_to"]
    bad = retained + b"zzz"
    mirror.write_bytes(bad)
    markers = {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")}
    assert markers == {marker: marker.read_bytes()}
    for _retry in range(2):
        assert main([*_argv(b), "ledger", "repair"]) == 2
        out, err = capsys.readouterr()
        assert "ledger.prose.mismatch" in err and "not a prefix" in err, err
        assert "; terminated" not in err and "terminated" not in out  # no newline written
        assert jsonl.read_bytes() == torn_jsonl and mirror.read_bytes() == bad
        assert {p: p.read_bytes() for p in b.state.glob("ledger-repair-pending*.json")} == markers
    mirror.write_bytes(retained)
    assert main([*_argv(b), "ledger", "repair"]) == 0
    out, err = capsys.readouterr()
    assert "terminated" in err
    assert jsonl.read_bytes() == torn_jsonl + b"\n"
    assert _no_markers(b) and main([*_argv(b), "ledger", "verify"]) == 0
    assert _actions(b).count("ledger.mirror_truncated") == 1
    assert _actions(b).count("ledger.tail_truncated") == 0
